// 通勤タイマー 時刻表データ
// 北総線 新柴又駅 ⇔ 京急線 品川駅（京成線経由・直通運転）
//
// ★ サンプルデータです。実際の時刻表に差し替えてください。
// フォーマット: { time: "HH:MM", type: "種別", dest: "行先" }

const TIMETABLE = {
  outbound: {
    // 行き: 新柴又駅 → 品川方面
    label: { from: "新柴又", to: "品川方面" },
    weekday: [
      { time: "05:30", type: "普通", dest: "品川" },
      { time: "05:48", type: "普通", dest: "品川" },
      { time: "06:02", type: "普通", dest: "品川" },
      { time: "06:15", type: "普通", dest: "品川" },
      { time: "06:28", type: "急行", dest: "品川" },
      { time: "06:35", type: "普通", dest: "品川" },
      { time: "06:42", type: "急行", dest: "品川" },
      { time: "06:50", type: "普通", dest: "品川" },
      { time: "06:58", type: "急行", dest: "品川" },
      { time: "07:05", type: "普通", dest: "品川" },
      { time: "07:12", type: "急行", dest: "品川" },
      { time: "07:20", type: "普通", dest: "品川" },
      { time: "07:28", type: "急行", dest: "品川" },
      { time: "07:35", type: "普通", dest: "品川" },
      { time: "07:43", type: "急行", dest: "品川" },
      { time: "07:50", type: "普通", dest: "品川" },
      { time: "07:58", type: "急行", dest: "品川" },
      { time: "08:05", type: "普通", dest: "品川" },
      { time: "08:12", type: "急行", dest: "品川" },
      { time: "08:20", type: "普通", dest: "品川" },
      { time: "08:30", type: "急行", dest: "品川" },
      { time: "08:42", type: "普通", dest: "品川" },
      { time: "08:55", type: "急行", dest: "品川" },
      { time: "09:10", type: "普通", dest: "品川" },
      { time: "09:25", type: "普通", dest: "品川" },
      { time: "09:40", type: "普通", dest: "品川" },
      { time: "10:00", type: "普通", dest: "品川" },
      { time: "10:20", type: "普通", dest: "品川" },
      { time: "10:40", type: "普通", dest: "品川" },
      { time: "11:00", type: "普通", dest: "品川" },
      { time: "11:20", type: "普通", dest: "品川" },
      { time: "11:40", type: "普通", dest: "品川" },
      { time: "12:00", type: "普通", dest: "品川" },
      { time: "12:20", type: "普通", dest: "品川" },
      { time: "12:40", type: "普通", dest: "品川" },
      { time: "13:00", type: "普通", dest: "品川" },
      { time: "13:20", type: "普通", dest: "品川" },
      { time: "13:40", type: "普通", dest: "品川" },
      { time: "14:00", type: "普通", dest: "品川" },
      { time: "14:20", type: "普通", dest: "品川" },
      { time: "14:40", type: "普通", dest: "品川" },
      { time: "15:00", type: "普通", dest: "品川" },
      { time: "15:20", type: "普通", dest: "品川" },
      { time: "15:40", type: "普通", dest: "品川" },
      { time: "16:00", type: "普通", dest: "品川" },
      { time: "16:20", type: "普通", dest: "品川" },
      { time: "16:40", type: "普通", dest: "品川" },
      { time: "17:00", type: "急行", dest: "品川" },
      { time: "17:15", type: "普通", dest: "品川" },
      { time: "17:30", type: "急行", dest: "品川" },
      { time: "17:45", type: "普通", dest: "品川" },
      { time: "18:00", type: "急行", dest: "品川" },
      { time: "18:15", type: "普通", dest: "品川" },
      { time: "18:30", type: "普通", dest: "品川" },
      { time: "18:50", type: "普通", dest: "品川" },
      { time: "19:10", type: "普通", dest: "品川" },
      { time: "19:30", type: "普通", dest: "品川" },
      { time: "19:50", type: "普通", dest: "品川" },
      { time: "20:10", type: "普通", dest: "品川" },
      { time: "20:30", type: "普通", dest: "品川" },
      { time: "20:50", type: "普通", dest: "品川" },
      { time: "21:10", type: "普通", dest: "品川" },
      { time: "21:30", type: "普通", dest: "品川" },
      { time: "21:50", type: "普通", dest: "品川" },
      { time: "22:10", type: "普通", dest: "品川" },
      { time: "22:30", type: "普通", dest: "品川" },
      { time: "22:55", type: "普通", dest: "品川" },
      { time: "23:20", type: "普通", dest: "品川" },
      { time: "23:45", type: "普通", dest: "品川" },
    ],
    holiday: [
      { time: "06:00", type: "普通", dest: "品川" },
      { time: "06:25", type: "普通", dest: "品川" },
      { time: "06:50", type: "普通", dest: "品川" },
      { time: "07:10", type: "普通", dest: "品川" },
      { time: "07:30", type: "普通", dest: "品川" },
      { time: "07:50", type: "普通", dest: "品川" },
      { time: "08:10", type: "普通", dest: "品川" },
      { time: "08:30", type: "普通", dest: "品川" },
      { time: "08:50", type: "普通", dest: "品川" },
      { time: "09:10", type: "普通", dest: "品川" },
      { time: "09:30", type: "普通", dest: "品川" },
      { time: "09:50", type: "普通", dest: "品川" },
      { time: "10:10", type: "普通", dest: "品川" },
      { time: "10:30", type: "普通", dest: "品川" },
      { time: "11:00", type: "普通", dest: "品川" },
      { time: "11:30", type: "普通", dest: "品川" },
      { time: "12:00", type: "普通", dest: "品川" },
      { time: "12:30", type: "普通", dest: "品川" },
      { time: "13:00", type: "普通", dest: "品川" },
      { time: "13:30", type: "普通", dest: "品川" },
      { time: "14:00", type: "普通", dest: "品川" },
      { time: "14:30", type: "普通", dest: "品川" },
      { time: "15:00", type: "普通", dest: "品川" },
      { time: "15:30", type: "普通", dest: "品川" },
      { time: "16:00", type: "普通", dest: "品川" },
      { time: "16:30", type: "普通", dest: "品川" },
      { time: "17:00", type: "普通", dest: "品川" },
      { time: "17:30", type: "普通", dest: "品川" },
      { time: "18:00", type: "普通", dest: "品川" },
      { time: "18:30", type: "普通", dest: "品川" },
      { time: "19:00", type: "普通", dest: "品川" },
      { time: "19:30", type: "普通", dest: "品川" },
      { time: "20:00", type: "普通", dest: "品川" },
      { time: "20:30", type: "普通", dest: "品川" },
      { time: "21:00", type: "普通", dest: "品川" },
      { time: "21:30", type: "普通", dest: "品川" },
      { time: "22:00", type: "普通", dest: "品川" },
      { time: "22:30", type: "普通", dest: "品川" },
      { time: "23:00", type: "普通", dest: "品川" },
      { time: "23:30", type: "普通", dest: "品川" },
    ],
  },
  inbound: {
    // 帰り: 品川駅 → 新柴又方面
    label: { from: "品川", to: "新柴又方面" },
    weekday: [
      { time: "05:35", type: "普通", dest: "印旛日本医大" },
      { time: "05:55", type: "普通", dest: "印旛日本医大" },
      { time: "06:15", type: "普通", dest: "印旛日本医大" },
      { time: "06:30", type: "普通", dest: "印旛日本医大" },
      { time: "06:45", type: "普通", dest: "印旛日本医大" },
      { time: "07:00", type: "普通", dest: "印旛日本医大" },
      { time: "07:15", type: "普通", dest: "印旛日本医大" },
      { time: "07:30", type: "普通", dest: "印旛日本医大" },
      { time: "07:45", type: "普通", dest: "印旛日本医大" },
      { time: "08:00", type: "普通", dest: "印旛日本医大" },
      { time: "08:20", type: "普通", dest: "印旛日本医大" },
      { time: "08:40", type: "普通", dest: "印旛日本医大" },
      { time: "09:00", type: "普通", dest: "印旛日本医大" },
      { time: "09:20", type: "普通", dest: "印旛日本医大" },
      { time: "09:40", type: "普通", dest: "印旛日本医大" },
      { time: "10:00", type: "普通", dest: "印旛日本医大" },
      { time: "10:20", type: "普通", dest: "印旛日本医大" },
      { time: "10:40", type: "普通", dest: "印旛日本医大" },
      { time: "11:00", type: "普通", dest: "印旛日本医大" },
      { time: "11:20", type: "普通", dest: "印旛日本医大" },
      { time: "11:40", type: "普通", dest: "印旛日本医大" },
      { time: "12:00", type: "普通", dest: "印旛日本医大" },
      { time: "12:20", type: "普通", dest: "印旛日本医大" },
      { time: "12:40", type: "普通", dest: "印旛日本医大" },
      { time: "13:00", type: "普通", dest: "印旛日本医大" },
      { time: "13:20", type: "普通", dest: "印旛日本医大" },
      { time: "13:40", type: "普通", dest: "印旛日本医大" },
      { time: "14:00", type: "普通", dest: "印旛日本医大" },
      { time: "14:20", type: "普通", dest: "印旛日本医大" },
      { time: "14:40", type: "普通", dest: "印旛日本医大" },
      { time: "15:00", type: "普通", dest: "印旛日本医大" },
      { time: "15:20", type: "普通", dest: "印旛日本医大" },
      { time: "15:40", type: "普通", dest: "印旛日本医大" },
      { time: "16:00", type: "普通", dest: "印旛日本医大" },
      { time: "16:15", type: "急行", dest: "印旛日本医大" },
      { time: "16:30", type: "普通", dest: "印旛日本医大" },
      { time: "16:45", type: "急行", dest: "印旛日本医大" },
      { time: "17:00", type: "普通", dest: "印旛日本医大" },
      { time: "17:12", type: "急行", dest: "印旛日本医大" },
      { time: "17:25", type: "普通", dest: "印旛日本医大" },
      { time: "17:38", type: "急行", dest: "印旛日本医大" },
      { time: "17:50", type: "普通", dest: "印旛日本医大" },
      { time: "18:02", type: "急行", dest: "印旛日本医大" },
      { time: "18:15", type: "普通", dest: "印旛日本医大" },
      { time: "18:28", type: "急行", dest: "印旛日本医大" },
      { time: "18:40", type: "普通", dest: "印旛日本医大" },
      { time: "18:55", type: "急行", dest: "印旛日本医大" },
      { time: "19:10", type: "普通", dest: "印旛日本医大" },
      { time: "19:25", type: "急行", dest: "印旛日本医大" },
      { time: "19:40", type: "普通", dest: "印旛日本医大" },
      { time: "19:55", type: "普通", dest: "印旛日本医大" },
      { time: "20:10", type: "普通", dest: "印旛日本医大" },
      { time: "20:30", type: "普通", dest: "印旛日本医大" },
      { time: "20:50", type: "普通", dest: "印旛日本医大" },
      { time: "21:10", type: "普通", dest: "印旛日本医大" },
      { time: "21:30", type: "普通", dest: "印旛日本医大" },
      { time: "21:50", type: "普通", dest: "印旛日本医大" },
      { time: "22:10", type: "普通", dest: "印旛日本医大" },
      { time: "22:30", type: "普通", dest: "印旛日本医大" },
      { time: "22:55", type: "普通", dest: "印旛日本医大" },
      { time: "23:15", type: "普通", dest: "印旛日本医大" },
      { time: "23:40", type: "普通", dest: "印旛日本医大" },
    ],
    holiday: [
      { time: "06:10", type: "普通", dest: "印旛日本医大" },
      { time: "06:40", type: "普通", dest: "印旛日本医大" },
      { time: "07:00", type: "普通", dest: "印旛日本医大" },
      { time: "07:20", type: "普通", dest: "印旛日本医大" },
      { time: "07:40", type: "普通", dest: "印旛日本医大" },
      { time: "08:00", type: "普通", dest: "印旛日本医大" },
      { time: "08:20", type: "普通", dest: "印旛日本医大" },
      { time: "08:40", type: "普通", dest: "印旛日本医大" },
      { time: "09:00", type: "普通", dest: "印旛日本医大" },
      { time: "09:20", type: "普通", dest: "印旛日本医大" },
      { time: "09:40", type: "普通", dest: "印旛日本医大" },
      { time: "10:00", type: "普通", dest: "印旛日本医大" },
      { time: "10:30", type: "普通", dest: "印旛日本医大" },
      { time: "11:00", type: "普通", dest: "印旛日本医大" },
      { time: "11:30", type: "普通", dest: "印旛日本医大" },
      { time: "12:00", type: "普通", dest: "印旛日本医大" },
      { time: "12:30", type: "普通", dest: "印旛日本医大" },
      { time: "13:00", type: "普通", dest: "印旛日本医大" },
      { time: "13:30", type: "普通", dest: "印旛日本医大" },
      { time: "14:00", type: "普通", dest: "印旛日本医大" },
      { time: "14:30", type: "普通", dest: "印旛日本医大" },
      { time: "15:00", type: "普通", dest: "印旛日本医大" },
      { time: "15:30", type: "普通", dest: "印旛日本医大" },
      { time: "16:00", type: "普通", dest: "印旛日本医大" },
      { time: "16:30", type: "普通", dest: "印旛日本医大" },
      { time: "17:00", type: "普通", dest: "印旛日本医大" },
      { time: "17:30", type: "普通", dest: "印旛日本医大" },
      { time: "18:00", type: "普通", dest: "印旛日本医大" },
      { time: "18:30", type: "普通", dest: "印旛日本医大" },
      { time: "19:00", type: "普通", dest: "印旛日本医大" },
      { time: "19:30", type: "普通", dest: "印旛日本医大" },
      { time: "20:00", type: "普通", dest: "印旛日本医大" },
      { time: "20:30", type: "普通", dest: "印旛日本医大" },
      { time: "21:00", type: "普通", dest: "印旛日本医大" },
      { time: "21:30", type: "普通", dest: "印旛日本医大" },
      { time: "22:00", type: "普通", dest: "印旛日本医大" },
      { time: "22:30", type: "普通", dest: "印旛日本医大" },
      { time: "23:00", type: "普通", dest: "印旛日本医大" },
      { time: "23:30", type: "普通", dest: "印旛日本医大" },
    ],
  },
};
