// 通勤タイマー 時刻表データ
// 北総線 新柴又駅 ⇔ 京急線 品川駅（京成線経由・直通運転）
// 出典: 駅探 (ekitan.com) 2025年12月13日現在
//
// 行き(outbound): 新柴又駅の全列車。via_shinagawa=false は品川を通らない電車
// 帰り(inbound): 品川駅から新柴又に停車する普通列車のみ抽出
//   ※11〜14時台(平日)・10〜19時台(土休日)は直通電車なし。泉岳寺で乗換が必要

const TIMETABLE = {
  outbound: {
    label: { from: "新柴又", to: "品川方面" },
    weekday: [
      { time: "05:31", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "05:49", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "06:08", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "06:30", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "06:45", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "07:02", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "07:12", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "07:23", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "07:32", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "07:43", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "07:52", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "08:03", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "08:12", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "08:23", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "08:33", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "08:45", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "08:58", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "09:08", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "09:22", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "09:29", type: "普通", dest: "三崎口", via_shinagawa: true },
      { time: "09:44", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "09:51", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "09:59", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "10:17", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "10:34", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "10:52", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "11:12", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "11:33", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "11:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "12:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "12:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "12:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "13:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "13:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "13:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "14:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "14:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "14:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "15:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "15:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "15:52", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "16:13", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "16:30", type: "普通", dest: "京急久里浜", via_shinagawa: true },
      { time: "16:36", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "16:53", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "17:10", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "17:17", type: "普通", dest: "押上", via_shinagawa: false },
      { time: "17:36", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "17:43", type: "普通", dest: "京急久里浜", via_shinagawa: true },
      { time: "17:55", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "18:04", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "18:17", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "18:32", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "18:47", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "19:05", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "19:18", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "19:33", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "19:54", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "20:00", type: "普通", dest: "京急久里浜", via_shinagawa: true },
      { time: "20:17", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "20:25", type: "普通", dest: "京急久里浜", via_shinagawa: true },
      { time: "20:37", type: "普通", dest: "押上", via_shinagawa: false },
      { time: "20:54", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "21:12", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "21:33", type: "普通", dest: "押上", via_shinagawa: false },
      { time: "21:37", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "21:47", type: "普通", dest: "三崎口", via_shinagawa: true },
      { time: "21:59", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "22:07", type: "普通", dest: "三崎口", via_shinagawa: true },
      { time: "22:19", type: "普通", dest: "押上", via_shinagawa: false },
      { time: "22:39", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "22:59", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "23:16", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "23:33", type: "普通", dest: "品川", via_shinagawa: true },
      { time: "23:50", type: "普通", dest: "泉岳寺", via_shinagawa: false },
    ],
    saturday: [
      { time: "05:31", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "05:49", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "06:07", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "06:29", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "06:44", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "07:04", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "07:23", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "07:42", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "07:58", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "08:09", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "08:26", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "08:41", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "08:57", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "09:11", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "09:31", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "09:54", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "10:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "10:33", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "10:52", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "11:13", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "11:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "11:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "12:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "12:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "12:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "13:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "13:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "13:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "14:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "14:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "14:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "15:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "15:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "15:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "16:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "16:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "16:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "17:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "17:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "17:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "18:12", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "18:32", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "18:53", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "19:16", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "19:30", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "19:47", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "20:11", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "20:30", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "20:48", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "21:04", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "21:31", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "21:46", type: "普通", dest: "押上", via_shinagawa: false },
      { time: "22:10", type: "普通", dest: "羽田空港", via_shinagawa: true },
      { time: "22:27", type: "普通", dest: "三浦海岸", via_shinagawa: true },
      { time: "22:47", type: "普通", dest: "西馬込", via_shinagawa: false },
      { time: "23:16", type: "普通", dest: "金沢文庫", via_shinagawa: true },
      { time: "23:50", type: "普通", dest: "泉岳寺", via_shinagawa: false },
    ],
    // 休日ダイヤは土曜と同一
    holiday: null,
  },
  inbound: {
    label: { from: "品川", to: "新柴又方面" },
    weekday: [
      // 品川発 → 新柴又停車の普通列車のみ（印旛日本医大行・印西牧の原行）
      { time: "05:28", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "05:46", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "07:11", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "07:20", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "07:30", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "07:52", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "08:24", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "09:30", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "09:48", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "10:09", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "10:29", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "10:49", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      // 11〜14時台: 品川からの直通なし。泉岳寺で浅草線に乗換
      { time: "15:29", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "15:49", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "15:58", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "16:19", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "16:38", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "17:13", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "17:45", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "17:56", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "18:16", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "18:26", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "18:38", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "18:46", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "19:05", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "19:28", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "19:55", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "21:09", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "22:23", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "22:59", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "23:31", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
    ],
    saturday: [
      // 品川発 → 新柴又停車の普通列車のみ
      { time: "05:47", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "07:03", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "07:47", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "08:07", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "08:27", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "08:47", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "08:57", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "09:17", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "09:36", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      // 10〜19時台: 品川からの直通なし。泉岳寺で浅草線に乗換
      { time: "20:17", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "20:57", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "21:17", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "21:37", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "21:47", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "21:59", type: "普通", dest: "印西牧の原", via_shinagawa: true },
      { time: "22:17", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "23:02", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
      { time: "23:31", type: "普通", dest: "印旛日本医大", via_shinagawa: true },
    ],
    // 休日ダイヤは土曜と同一
    holiday: null,
  },
};

// 休日ダイヤは土曜と同一なのでコピー
TIMETABLE.outbound.holiday = TIMETABLE.outbound.saturday;
TIMETABLE.inbound.holiday = TIMETABLE.inbound.saturday;
